server:
    port: 8099
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:mysql://localhost:3306/dbuser
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimumIdle: 2
            maximumPoolSize: 5
            cachePrepStmts: true
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
            